/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package NumeroMaiorQueDez;

import java.util.Scanner;

public class App {

    public static void main(String[] args){
        
        int numero = 0;
        
        Scanner ltor = new Scanner(System.in);
        
        System.out.println("Digite um numero: ");
        numero = ltor.nextInt();
        
        if(numero > 10){
            System.out.println("O numero informado e maior que 10");
        }else{
            System.out.println("O numero informado e menor que 10");
        }

    }
}
